app:
  file_directory: "/home/kiling/email-data"
  max_text_message_size: 64
  mark_as_read_messages: true
  mail_check_timeout: 60

imap:
  imap_server: "imap.yandex.ru:993"
  login: ""
  password: ""

telegram:
  bot_token: ""
  AllowedUserId: 123