app:
  file_directory: "/home/kiling/email-data"
  max_text_message_size: 64
  mark_as_read_messages: true
  mail_check_timeout: 60

imap:
  imap_server: "imap.yandex.ru:993"
  login: "kirillkiling@yandex.ru"
  password: "ohgpmesvsbsyiuod"

telegram:
  bot_token: "5233362724:AAEkoWRxYvvV1gXdamEix_Ej8nzWixx1jXI"
  allowed_user_id:
    - 594785598
